version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
      - youtube-notes
  graphql-engine:
    image: hasura/graphql-engine:v1.1.1
    depends_on:
    - "postgres"
    restart: always
    networks:
      - youtube-notes
  elm:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ["make"]
    links:
      - graphql-engine
    networks:
      - youtube-notes
volumes:
  db_data:

networks:
  youtube-notes:
